/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SecondService.h"
#include "thrift/async/TAsyncChannel.h"
#include "SecondService.tcc"

namespace thrift { namespace test {


SecondService_secondtestString_args::~SecondService_secondtestString_args() noexcept {
}


SecondService_secondtestString_pargs::~SecondService_secondtestString_pargs() noexcept {
}


SecondService_secondtestString_result::~SecondService_secondtestString_result() noexcept {
}


SecondService_secondtestString_presult::~SecondService_secondtestString_presult() noexcept {
}

}} // namespace

