/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftTest.h"
#include "thrift/async/TAsyncChannel.h"
#include "ThriftTest.tcc"

namespace thrift { namespace test {


ThriftTest_testVoid_args::~ThriftTest_testVoid_args() noexcept {
}


ThriftTest_testVoid_pargs::~ThriftTest_testVoid_pargs() noexcept {
}


ThriftTest_testVoid_result::~ThriftTest_testVoid_result() noexcept {
}


ThriftTest_testVoid_presult::~ThriftTest_testVoid_presult() noexcept {
}


ThriftTest_testString_args::~ThriftTest_testString_args() noexcept {
}


ThriftTest_testString_pargs::~ThriftTest_testString_pargs() noexcept {
}


ThriftTest_testString_result::~ThriftTest_testString_result() noexcept {
}


ThriftTest_testString_presult::~ThriftTest_testString_presult() noexcept {
}


ThriftTest_testBool_args::~ThriftTest_testBool_args() noexcept {
}


ThriftTest_testBool_pargs::~ThriftTest_testBool_pargs() noexcept {
}


ThriftTest_testBool_result::~ThriftTest_testBool_result() noexcept {
}


ThriftTest_testBool_presult::~ThriftTest_testBool_presult() noexcept {
}


ThriftTest_testByte_args::~ThriftTest_testByte_args() noexcept {
}


ThriftTest_testByte_pargs::~ThriftTest_testByte_pargs() noexcept {
}


ThriftTest_testByte_result::~ThriftTest_testByte_result() noexcept {
}


ThriftTest_testByte_presult::~ThriftTest_testByte_presult() noexcept {
}


ThriftTest_testI32_args::~ThriftTest_testI32_args() noexcept {
}


ThriftTest_testI32_pargs::~ThriftTest_testI32_pargs() noexcept {
}


ThriftTest_testI32_result::~ThriftTest_testI32_result() noexcept {
}


ThriftTest_testI32_presult::~ThriftTest_testI32_presult() noexcept {
}


ThriftTest_testI64_args::~ThriftTest_testI64_args() noexcept {
}


ThriftTest_testI64_pargs::~ThriftTest_testI64_pargs() noexcept {
}


ThriftTest_testI64_result::~ThriftTest_testI64_result() noexcept {
}


ThriftTest_testI64_presult::~ThriftTest_testI64_presult() noexcept {
}


ThriftTest_testDouble_args::~ThriftTest_testDouble_args() noexcept {
}


ThriftTest_testDouble_pargs::~ThriftTest_testDouble_pargs() noexcept {
}


ThriftTest_testDouble_result::~ThriftTest_testDouble_result() noexcept {
}


ThriftTest_testDouble_presult::~ThriftTest_testDouble_presult() noexcept {
}


ThriftTest_testBinary_args::~ThriftTest_testBinary_args() noexcept {
}


ThriftTest_testBinary_pargs::~ThriftTest_testBinary_pargs() noexcept {
}


ThriftTest_testBinary_result::~ThriftTest_testBinary_result() noexcept {
}


ThriftTest_testBinary_presult::~ThriftTest_testBinary_presult() noexcept {
}


ThriftTest_testStruct_args::~ThriftTest_testStruct_args() noexcept {
}


ThriftTest_testStruct_pargs::~ThriftTest_testStruct_pargs() noexcept {
}


ThriftTest_testStruct_result::~ThriftTest_testStruct_result() noexcept {
}


ThriftTest_testStruct_presult::~ThriftTest_testStruct_presult() noexcept {
}


ThriftTest_testNest_args::~ThriftTest_testNest_args() noexcept {
}


ThriftTest_testNest_pargs::~ThriftTest_testNest_pargs() noexcept {
}


ThriftTest_testNest_result::~ThriftTest_testNest_result() noexcept {
}


ThriftTest_testNest_presult::~ThriftTest_testNest_presult() noexcept {
}


ThriftTest_testMap_args::~ThriftTest_testMap_args() noexcept {
}


ThriftTest_testMap_pargs::~ThriftTest_testMap_pargs() noexcept {
}


ThriftTest_testMap_result::~ThriftTest_testMap_result() noexcept {
}


ThriftTest_testMap_presult::~ThriftTest_testMap_presult() noexcept {
}


ThriftTest_testStringMap_args::~ThriftTest_testStringMap_args() noexcept {
}


ThriftTest_testStringMap_pargs::~ThriftTest_testStringMap_pargs() noexcept {
}


ThriftTest_testStringMap_result::~ThriftTest_testStringMap_result() noexcept {
}


ThriftTest_testStringMap_presult::~ThriftTest_testStringMap_presult() noexcept {
}


ThriftTest_testSet_args::~ThriftTest_testSet_args() noexcept {
}


ThriftTest_testSet_pargs::~ThriftTest_testSet_pargs() noexcept {
}


ThriftTest_testSet_result::~ThriftTest_testSet_result() noexcept {
}


ThriftTest_testSet_presult::~ThriftTest_testSet_presult() noexcept {
}


ThriftTest_testList_args::~ThriftTest_testList_args() noexcept {
}


ThriftTest_testList_pargs::~ThriftTest_testList_pargs() noexcept {
}


ThriftTest_testList_result::~ThriftTest_testList_result() noexcept {
}


ThriftTest_testList_presult::~ThriftTest_testList_presult() noexcept {
}


ThriftTest_testEnum_args::~ThriftTest_testEnum_args() noexcept {
}


ThriftTest_testEnum_pargs::~ThriftTest_testEnum_pargs() noexcept {
}


ThriftTest_testEnum_result::~ThriftTest_testEnum_result() noexcept {
}


ThriftTest_testEnum_presult::~ThriftTest_testEnum_presult() noexcept {
}


ThriftTest_testTypedef_args::~ThriftTest_testTypedef_args() noexcept {
}


ThriftTest_testTypedef_pargs::~ThriftTest_testTypedef_pargs() noexcept {
}


ThriftTest_testTypedef_result::~ThriftTest_testTypedef_result() noexcept {
}


ThriftTest_testTypedef_presult::~ThriftTest_testTypedef_presult() noexcept {
}


ThriftTest_testMapMap_args::~ThriftTest_testMapMap_args() noexcept {
}


ThriftTest_testMapMap_pargs::~ThriftTest_testMapMap_pargs() noexcept {
}


ThriftTest_testMapMap_result::~ThriftTest_testMapMap_result() noexcept {
}


ThriftTest_testMapMap_presult::~ThriftTest_testMapMap_presult() noexcept {
}


ThriftTest_testInsanity_args::~ThriftTest_testInsanity_args() noexcept {
}


ThriftTest_testInsanity_pargs::~ThriftTest_testInsanity_pargs() noexcept {
}


ThriftTest_testInsanity_result::~ThriftTest_testInsanity_result() noexcept {
}


ThriftTest_testInsanity_presult::~ThriftTest_testInsanity_presult() noexcept {
}


ThriftTest_testMulti_args::~ThriftTest_testMulti_args() noexcept {
}


ThriftTest_testMulti_pargs::~ThriftTest_testMulti_pargs() noexcept {
}


ThriftTest_testMulti_result::~ThriftTest_testMulti_result() noexcept {
}


ThriftTest_testMulti_presult::~ThriftTest_testMulti_presult() noexcept {
}


ThriftTest_testException_args::~ThriftTest_testException_args() noexcept {
}


ThriftTest_testException_pargs::~ThriftTest_testException_pargs() noexcept {
}


ThriftTest_testException_result::~ThriftTest_testException_result() noexcept {
}


ThriftTest_testException_presult::~ThriftTest_testException_presult() noexcept {
}


ThriftTest_testMultiException_args::~ThriftTest_testMultiException_args() noexcept {
}


ThriftTest_testMultiException_pargs::~ThriftTest_testMultiException_pargs() noexcept {
}


ThriftTest_testMultiException_result::~ThriftTest_testMultiException_result() noexcept {
}


ThriftTest_testMultiException_presult::~ThriftTest_testMultiException_presult() noexcept {
}


ThriftTest_testOneway_args::~ThriftTest_testOneway_args() noexcept {
}


ThriftTest_testOneway_pargs::~ThriftTest_testOneway_pargs() noexcept {
}

}} // namespace

