/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AnnotationTest_constants.h"



const AnnotationTestConstants g_AnnotationTest_constants;

AnnotationTestConstants::AnnotationTestConstants() {
}



