/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OneWayTest_constants.h"

namespace onewaytest {

const OneWayTestConstants g_OneWayTest_constants;

OneWayTestConstants::OneWayTestConstants() {
}

} // namespace

